version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/db_blogpessoal?createDatabaseIfNotExist=true&serverTimezone=America/Sao_Paulo&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_PROFILES_ACTIVE: prod
    command: ["./wait-for-it.sh", "mysql:3306", "--", "java", "-jar", "app.jar"]
     

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_blogpessoal
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"

      
  wait-for-it:
    image: busybox
    entrypoint: ["sh", "-c", "while ! nc -z mysql 3306; do sleep 1; done;"]